version: '3.7'
services:
  openldap2:
    image: osixia/openldap:1.4.0
    container_name: openldap2
    environment:
      LDAP_ORGANISATION: "Confluent"
      LDAP_DOMAIN: "ps.confluent.io"
      LDAP_BASE_DN: "dc=ps,dc=confluent,dc=io"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    volumes:
      - ./provisioners/ansible/roles/ldap/files/ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - "389:389"
      - "636:636"
    command: "--copy-service --loglevel debug"
  phpldapadmin2:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap2