---
- name: Install Portainer
  docker_container:
    image: portainer/portainer-ce:latest
    name: portainer
    privileged: yes
    restart_policy: always
    state: started
    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9000:9000"
  become: true