---
# Role to deploy pipelines on a given streamsets instance / URL.
- hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  user: vagrant
  vars:
    vault_user: "vagrant"
    vault_group: "vagrant"
    vault_version: 1.11.3
  roles:
    - vault
    - portainer
