---
- name: Install Vault Docker
  docker_container:
    image: vault:latest
    name: vault
    privileged: yes
    restart_policy: always
    state: started
#    volumes:
#      - /home/vagrant/provisioners/ansible/roles/vault/files/config:/vault/config
#      - /home/vagrant/provisioners/ansible/roles/vault/files/:/vault/file
    ports:
      - "8200:8200"
#    cap_add:
#      - IPC_LOCK
    env:
      VAULT_ADDR: "http://localhost:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
      VAULT_TOKEN: "vault-plaintext-root-token"
#    entrypoint: vault server dev -config /vault/config.hcl
  become: true

#- name: Creating vault user group
#  group:
#    name: "{{ vault_group }}"
#  become: true
#- name: Creating vault user
#  user:
#    name: "{{ vault_user }}"
#    group: "{{ vault_group }}"
#    system: yes
#    shell: "/sbin/nologin"
#    comment: "vault nologin User"
#    createhome: "no"
#    state: present
#- name: Install prerequisites
#  package:
#    name: "{{ item }}"
#    update_cache: yes
#  with_items: "{{ vault_install_prerequisites }}"
#  become: yes
#- name: Download binary
#  get_url:
#    url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
#    dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
#    owner: "{{ vault_user }}"
#    group: "{{ vault_group }}"
#    mode: 0755
##    checksum: "{{vault_checksum}}"
#  register: vault_download
#- name: "Unzip vault archive"
#  unarchive:
#    src: "{{ vault_download.dest }}"
#    dest: /usr/local/bin
#    copy: no
#    owner: "{{ vault_user }}"
#    group: "{{ vault_group }}"
#    mode: 0755